version: '2'
services:
    segundoparcialproyecto-postgresql:
        image: postgres:10.4
        # volumes:
        #     - ~/volumes/jhipster/segundoparcialproyecto/postgresql/:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=segundoparcialproyecto
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
